# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d49fab652c91d6564bd0048ca3660c9eafde0bb4fca40a9596f1ed40fffaaf74889c2e8f8d725299d9be781156b5730b5ba61287f742181932e6a31fb3eb5ab

test:
  secret_key_base: 6e16cf4d1783e061ff3426be6058e35bda62b369cf391ba3c624f459d0a1b7ac52f03e1fd490525e5c541a7bcf357dea9686e70a285448b939113377fcb4ecbc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
